version: '3.8'

services:
  todo-app:
    build: .
    container_name: todo-app
    image: todo-app:latest
    ports:
    - 3000:3000
    env_file:
    - .env
    depends_on:
    - mongo
    restart: always
  
  mongo:
    image: mongo:8.0
    container_name: mongodb
    ports:
    - 27017:27017
    volumes:
    - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
